import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";

export async function POST(req: Request) {
  try {
    // 1. Auth check
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json(
        { error: "Authentication required" },
        { status: 401 }
      );
    }

    // 2. Parse request
    const body = await req.json();
    const { imageUrl, title } = body;

    if (!imageUrl) {
      return NextResponse.json(
        { error: "imageUrl is required" },
        { status: 400 }
      );
    }

    // 3. If the image is a base64 data URL, upload to Supabase Storage first
    let finalImageUrl = imageUrl;

    if (imageUrl.startsWith("data:")) {
      const matches = imageUrl.match(/^data:([^;]+);base64,(.+)$/);
      if (matches) {
        const mimeType = matches[1];
        const base64Data = matches[2];
        const ext = mimeType.split("/")[1] || "png";
        const fileName = `tryon_${user.id}_${Date.now()}.${ext}`;
        const buffer = Buffer.from(base64Data, "base64");

        const { data: uploadData, error: uploadError } = await supabase.storage
          .from("wardrobe-images")
          .upload(fileName, buffer, {
            contentType: mimeType,
            upsert: false,
          });

        if (uploadError) {
          console.warn("[Wardrobe Add] Storage upload failed, using inline URL:", uploadError);
        } else {
          const { data: { publicUrl } } = supabase.storage.from("wardrobe-images").getPublicUrl(uploadData.path);
          finalImageUrl = publicUrl;
        }
      }
    } else if (imageUrl.startsWith("http")) {
      // Fetch the remote image (e.g. from ngrok) and upload to Supabase
      try {
        const imgRes = await fetch(imageUrl, {
          headers: { "ngrok-skip-browser-warning": "true" }
        });
        if (imgRes.ok) {
          const arrayBuffer = await imgRes.arrayBuffer();
          const buffer = Buffer.from(arrayBuffer);
          const mimeType = imgRes.headers.get("content-type") || "image/jpeg";
          const ext = mimeType.split("/")[1] || "jpg";
          const fileName = `tryon_${user.id}_${Date.now()}.${ext}`;

          const { data: uploadData, error: uploadError } = await supabase.storage
            .from("wardrobe-images")
            .upload(fileName, buffer, {
              contentType: mimeType,
              upsert: false,
            });

          if (uploadError) {
            console.warn("[Wardrobe Add] HTTP image upload failed, using original URL:", uploadError);
          } else {
            const { data: { publicUrl } } = supabase.storage.from("wardrobe-images").getPublicUrl(uploadData.path);
            finalImageUrl = publicUrl;
          }
        }
      } catch (fetchErr) {
        console.warn("[Wardrobe Add] Failed to fetch HTTP image:", fetchErr);
      }
    }

    // 4. Insert into wardrobe_items
    const itemName = title || "AI Try-On Result";
    const productData = {
      name: itemName,
      tag: "AI Try-On",
      price: "—",
      sizes: ["M"],
      desc: `Virtual try-on generated by Darpan AI on ${new Date().toLocaleDateString()}`,
      image_url: finalImageUrl,
      user_id: user.id,
    };

    const { data, error } = await supabase
      .from("wardrobe_items")
      .insert([productData])
      .select();

    if (error) {
      console.error("[Wardrobe Add] DB insert error:", error);
      return NextResponse.json({ error: `Database error: ${error.message}` }, { status: 500 });
    }

    return NextResponse.json({ success: true, data: data[0] });
  } catch (error) {
    console.error("[Wardrobe Add] Error:", error);
    return NextResponse.json(
      { error: "Failed to add item to wardrobe" },
      { status: 500 }
    );
  }
}
