'use client'

const galleryItems = Array(15).fill(null)

export function Gallery() {
    return (
        <section className="w-full py-20 px-4 bg-background">
            <div className="container mx-auto">
                <div className="text-center mb-12">
                    <h2 className="text-3xl md:text-4xl font-bold mb-4">
                        Limitless Styles, Generated by Our{' '}
                        <span className="text-primary">Virtual</span>
                        <br />
                        <span className="text-primary">Try On Engine</span>
                    </h2>
                    <p className="text-muted-foreground max-w-3xl mx-auto text-sm">
                        Explore generated unique looks. Create endless combinations of your favorite styles using unlimited mix-and-match technology.
                    </p>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-5 gap-3 max-w-6xl mx-auto mb-8">
                    {galleryItems.map((_, idx) => (
                        <div
                            key={idx}
                            className="aspect-square bg-gray-200 rounded-lg hover:shadow-md transition cursor-pointer"
                        ></div>
                    ))}
                </div>

                <div className="text-center">
                    <button className="px-8 py-3 bg-primary text-white rounded font-semibold hover:bg-accent transition">
                        Explore Full Catalog
                    </button>
                </div>
            </div>
        </section>
    )
}
